site_name: slippers
site_description: Build reusable components in Django without writing a single line of Python.
site_url: https://mitchel.me/slippers/
site_author: Mitchel Cabuloy
repo_url: https://github.com/mixxorz/slippers
repo_name: mixxorz/slippers

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/logo.svg
  favicon: img/favicon.ico

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Registering Components: registering-components.md
  - Using Components: using-components.md
  - Template Tags & Filters: template-tags-filters.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - extra.css

plugins:
  - search
