name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Node.js dependencies
        run: |
          cd ui
          npm ci --no-option --no-audit --progress=false

      - name: Build error UI
        env:
          GENERATE_SOURCEMAP: "false"
        run: |
          cd ui
          npm run build

      - name: Build the distribution
        run: |
          poetry build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
